# Generated by Django 2.2.1 on 2019-05-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='judge',
            name='sponsor_judge',
            field=models.BooleanField(default=False),
        ),
    ]
