# Generated by Django 2.2.1 on 2019-05-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0002_auto_20190523_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='first_name',
            field=models.CharField(default='test-first-name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judge',
            name='last_name',
            field=models.CharField(default='test-last-name', max_length=50),
            preserve_default=False,
        ),
    ]
