# Generated by Django 2.2.1 on 2019-07-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0004_judge_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
